openapi: "3.0.0"
info:
  description: "API specification"
  version: "0.0.5"
  title: "mm4sight"

tags:
- name: "model"
  description: "Prediction model related api's for forecasts, confidence intervals and explanations"
servers:
  - url: http://localhost:5000/
    description: Local test server
  - url: http://mm4sight.mybluemix.net/
    description: Deployment server
    
paths:
  /predict:
    summary: Generate a set of forecasts for a source country.
    description: Given a source `country`, `year`, and optionally any `scenario` paramaters, returns a point forecast, confidence interval, and explanations.
    get:
      tags:
      - model
      parameters:
      - name: source
        in: query
        description: Source country from which to forecast. ISO-3 code.
        example: 'ETH'
        schema:
          type: string
        required: true
      - name: year
        in: query
        description: Year for which the forecast is requested.
        example: 2016
        schema:
          type: integer
        required: true
      - name: scenario
        in: query
        required: false
        description: Indicator clusters names along with labels indicating relative change with respect to Sub-Saharan African countries. Cluster themes currently supported are `societal`, `health`, `food-security`, `infrastructure`, and `conflict`.
        schema:
          type: object
          properties:
            societal:
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: good
            health: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
            food-security: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
            infrastructure: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
            conflict: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
        style: form
        explode: true
      responses:
        '200':
          description: A valid forecast response with a point forecast, a 95% confidence interval (CI) and a explanation set.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastResponse'
        '405':
          description: "Invalid input"

components:
  schemas:
    ScenarioValues:
      type: string
      title: Labels for indicator themes
      description: Permitted labels for indicator cluster themes.
      enum:
      - worse
      - poor
      - average
      - good
      - best
    ForecastResponse:
      title: Forecast Response object
      type: "array"
      items:
        type: object  
        properties:
          target:
            type: "string"
            description: The ISO-3 code of the destination country (e.g. ZAF)
          forecast:
            type: "number"
            format: "float64"
            description: Point forecast associated with the source->target flow.
          CI:
            type: "array"
            description: Confidence interval associated with the point forecast.
            items:
              type: "number"
              format: "float64"
          explanation:
            type: "array"
            description: Features and magnitude associated with the point forecast
            items: 
              type: "object"
          status:
            type: "string"
          year :
            description: Year in the input query
            type: "integer"
          scenario:
            description: "Scenario in the input query (if any)"
            type: "array"
            items:
              type: "object"