openapi: "3.0.0"
info:
  description: "API specification"
  version: "0.1.0"
  title: "Foresight"

tags:
- name: "model"
  description: "Model related api's for forecasts, confidence intervals, scenarios and explanations"
- name: "indicators"
  description: "Calls related to indicator level data, outliers"
servers:
  - url: http://localhost:5000/
    description: Local test server
  - url: http://foresight.mybluemix.net/
    description: Deployment server
    
paths:
  /scenarios:
    summary: Returns supported scenarios for the model. 
    description: A Scenario is defined by a theme, and associated indicator variables. 
    get:
      tags: 
      - model
      parameters: []
      responses:
        '200':
          description: A response object that contains user labels, thematic cluster definitions with component indicators.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioResponse'
    
  /predict:
    summary: Generate a set of forecasts for a source country.
    description: Given a source `country`, `year`, and optionally any `scenario` paramaters, returns a point forecast, confidence interval, and explanations.
    get:
      tags:
      - model
      parameters:
      - name: source
        in: query
        description: Source country from which to forecast. ISO-3 code.
        example: 'ETH'
        schema:
          type: string
        required: true
      - name: year
        in: query
        description: Year for which the forecast is requested.
        example: 2016
        schema:
          type: integer
        required: true
      - name: scenario
        in: query
        required: false
        description: Indicator clusters names along with labels indicating relative change with respect to Sub-Saharan African countries. Cluster themes currently supported are `societal`, `health`, `food-security`, `infrastructure`, and `conflict`.
        schema:
          type: object
          properties:
            societal:
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: good
            health: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
            food-security: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
            infrastructure: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
            conflict: 
              type: string
              enum: 
              - worse
              - poor
              - average
              - good
              - best
              example: average
        style: form
        explode: true
      responses:
        '200':
          description: A valid forecast response with a point forecast, a 95% confidence interval (CI) and a explanation set.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastResponse'
        '405':
          description: "Invalid input"

components:
  schemas:
    ScenarioResponse:
      type: "array"
      title: Scenario definitions
      items:
        type: "object"
        properties:
          labels:
            type: "array"
            description: Set of user-facing labels that describe change in theme variables.
            items:
              type: "string"
              description: User label
          clusters:
            type: "array"
            description: A set of theme's supported by model
            items: 
              type: "object"
              properties:
                theme: 
                  type: "string"
                  description: Theme label
                indicators:
                  type: "array"
                  description: Set of indicators within the theme
                  items:
                    type: "object"
                    properties:
                      code:
                        type: "string"
                        description: Indicator code
                      description:
                        type: "string"
                        description: Indicator description
                      direction-improvement:
                        type: "string"
                        description: Order of indicator that represents improvement (higher/lower)

      
    ForecastResponse:
      title: Forecast Response object
      type: "array"
      items:
        type: object  
        properties:
          target:
            type: "string"
            description: The ISO-3 code of the destination country (e.g. ZAF)
          forecast:
            type: "number"
            format: "float64"
            description: Point forecast associated with the source->target flow.
          CI:
            type: "array"
            description: Confidence interval associated with the point forecast.
            items:
              type: "number"
              format: "float64"
          explanation:
            type: "array"
            description: Features and magnitude associated with the point forecast
            items: 
              type: "object"
          status:
            type: "string"
          year :
            description: Year in the input query
            type: "integer"
          scenario:
            description: "Scenario in the input query (if any)"
            type: "array"
            items:
              type: "object"